name: Build

on:
  push:
    branches:
      - master
      - develop
    tags:
      - "v*.*.*"
    paths-ignore:
      - LICENSE
      - "*.md"
      - .vscode
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository and submodules
      - uses: actions/checkout@v4.2.2
        with:
          submodules: recursive

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              build-essential \
              qtbase5-dev \
              libqt5websockets5-dev \
              qtwebengine5-dev \
              qttools5-dev \
              qt5keychain-dev \
              openconnect
              
      - name: Build
        run: |
          ./cmakew -B build \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_CXX_FLAGS_RELEASE=-s
          
          MAKEFLAGS=-j$(nproc) ./cmakew --build build

      - name: Package
        run: |
          cpack -G DEB
          ls
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: deb
          path: ./*.deb

  release-github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4.1.8
        with:
          name: release-source-code
          path: artifacts
      - uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "./artifacts/*.tar.gz"
          tag: "v1.4.9"
