name: Build

on:
  push:
    branches:
      - master
      - develop
    tags:
      - "v*.*.*"
    paths-ignore:
      - LICENSE
      - "*.md"
      - .vscode
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository and submodules
      - uses: actions/checkout@v4.2.2
        with:
          submodules: recursive
            
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              build-essential \
              qtbase5-dev \
              libqt5websockets5-dev \
              qtwebengine5-dev \
              qttools5-dev \
              qt5keychain-dev \
              openconnect \
              rpm \
              libx11-dev \
              libfuse2

      - name: Build
        run: |
          ./cmakew -B build \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_CXX_FLAGS_RELEASE=-s
          
          MAKEFLAGS=-j$(nproc) ./cmakew --build build

      - name: Package DEB and RPM
        run: |
          cd build
          cpack

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4.4.3
        with:
          name: packages
          path: |
            ./build/*.deb
            ./build/*.rpm
            ./build/*.AppImage

  release-github:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4.1.8
        with:
          name: packages
          path: artifacts
      - uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "./artifacts/*.{deb,rpm}"
          tag: "v1.4.9"

