name: Build

on:
  push:
    branches:
      - master
      - develop
    tags:
      - "v*.*.*"
    paths-ignore:
      - LICENSE
      - "*.md"
      - .vscode
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository and submodules
      - uses: actions/checkout@v4.2.2
        with:
          submodules: recursive

      - name: Build
        run: |
          ./scripts/install-ubuntu.sh
          # assert no library missing
          test $(ldd $(which gpclient) | grep 'not found' | wc -l) -eq 0

  snapshot-archive-all:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git-archive-all

      - name: Archive all
        run: |
          ./scripts/snapshot-archive-all.sh

      - name: Verify debian package
        run: |
          ./scripts/verify-debian-package.sh

      - uses: actions/upload-artifact@v4.4.3
        with:
          name: snapshot-source-code
          path: ./artifacts/*

  release-archive-all:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git-archive-all

      - name: Archive all
        run: |
          ./scripts/release-archive-all.sh

      - name: Verify debian package
        run: |
          ./scripts/verify-debian-package.sh

      - uses: actions/upload-artifact@v4.4.3
        with:
          name: release-source-code
          path: ./artifacts/*

  release-github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4.1.8
        with:
          name: release-source-code
          path: artifacts
      - uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "./artifacts/*.tar.gz"
          tag: "v1.4.9"
